version: '3.9'

services:
  postgres:
    container_name: appointment-postgres
    image: postgres:14.0
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: appointment-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis
    env_file:
      - .env

volumes:
  postgres:
  redis:
